version: "3"
services:
  app:
    image: us-central1-docker.pkg.dev/reimagined-robot/registry/app:latest
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: default
    ports:
    - 8000:8000
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: default
