version: "3"
services:
  app:
    image: us-central1-docker.pkg.dev/reimagined-robot/registry/app:latest
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://root:secret@postgres/default
    ports:
    - 8080:8080
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: default
